# Banco H2 (memória - só pra desenvolvimento)
spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Console H2 (acessar no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console